### ISSUE TITLE
trouble creating a Kubernetes Cluster

### ISSUE THREAD

**Issue by icrtiou** [amygdala/tensorflow-workshop#13]
trying to follow your readme creating a 3 node cluster with machine type **n1-highmem-8**

always get this error message:

> EXTERNAL: Insufficient regional quota to satisfy request for resource: "CPUS". The request requires '24.0' and is short '16.0'. The regional quota is '8.0' with '8.0' available.

Is this default quota limitation for trial account?

**Comment by elibixby** [comment]
Yes. I believe it is. 24 is the default quota for people not on the free trial. I'll update the docs when I move them to a new repo.
