### ISSUE TITLE
How to do prediction after training the wide and deep classifier? How to run locally?

### ISSUE THREAD

**Issue by QaisarRajput** [amygdala/tensorflow-workshop#71]
The notebook samples jump into Google Cloud deployment. But how to do the actual predictions on local machine. Lets say i have few rows having all the FEATURE_COLUMNS and i want to give those to the trained model and let it predict the label (in our case income_bracket). A small sample will help alot

**Comment by yufengg** [comment]
I've added an example of calling `estimator.predict` using a file containing a few rows of data near the end of the notebook. Hope it helps: https://github.com/amygdala/tensorflow-workshop/blob/master/workshop_sections/wide_n_deep/wide_n_deep_flow3.ipynb

**Comment by QaisarRajput** [comment]
Great!, Thanks @yufengg

**Comment by AshutoshDongare** [comment]
Check out this sample for [performing local predictions on Tensorflow Wide and Deep and save the results to CSV](https://github.com/AshutoshDongare/Tensorflow-Wide-Deep-Local-Prediction)
